// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avgaqbmowxatdbmxrikv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2Z2FxYm1vd3hhdGRibXhyaWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODU1MzgsImV4cCI6MjA2NjY2MTUzOH0.3B5N_a7TQiKGvSMhPC0XIGEoe4rJXDqpLaUguCGfJEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);